import time

time.sleep(1.5)
print("0%   █▒▒▒▒▒▒▒▒▒")
time.sleep(1.5)
print("10%  ███▒▒▒▒▒▒▒")
time.sleep(1.5)
print("30%  █████▒▒▒▒▒")
time.sleep(1.5)
print("50%  ███████▒▒▒")
time.sleep(1.5)
print("100% ██████████")
time.sleep(1.5)
print("")
print("█▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀█")
time.sleep(0.5)
print("█░░╦─╦╔╗╦─╔╗╔╗╔╦╗╔╗░░█")
time.sleep(0.5)
print("█░░║║║╠─║─║─║║║║║╠─░░█")
time.sleep(0.5)
print("█░░╚╩╝╚╝╚╝╚╝╚╝╩─╩╚╝░░█")
time.sleep(0.5)
print("█▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄█")
