import time

time.sleep(1.5)
print("0%   █▒▒▒▒▒▒▒▒▒")
print("")
time.sleep(1.5)
print("10%  ███▒▒▒▒▒▒▒")
print("")
time.sleep(1.5)
print("30%  █████▒▒▒▒▒")
print("")
time.sleep(1.5)
print("50%  ███████▒▒▒")
print("")
time.sleep(1.5)
print("100% ██████████")
time.sleep(1.5)
print("")
print("█▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀█")
time.sleep(0.5)
print("█░░╦─╦╔╗╦─╔╗╔╗╔╦╗╔╗░░█")
time.sleep(0.5)
print("█░░║║║╠─║─║─║║║║║╠─░░█")
time.sleep(0.5)
print("█░░╚╩╝╚╝╚╝╚╝╚╝╩─╩╚╝░░█")
time.sleep(0.5)
print("█▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄█")
print("")
time.sleep(0.5)
print("O que vocẽ deseja fazer?")
time.sleep(0.25)
print("1. Fazer operações basicas")
time.sleep(0.25)
print("2.")
time.sleep(0.25)
print("3.")
time.sleep(0.5)

Escolha = int(input())

if Escolha == 1:
    print("Escolha a operação:")
    time.sleep(0.5)
    print("1.Adição")
    time.sleep(0.25)
    print("2.Subtração")
    time.sleep(0.25)
    print("3.Multiplicação")
    time.sleep(0.25)
    print("4.Divisão")
    time.sleep(0.5)

Operacao = int(input())

if Operacao == 1:
    print("Escolha quantos números deseja somar:")
    time.sleep(0.5)
    print("1. dois números")
    time.sleep(0.25)
    print("2. três números")
    time.sleep(0.25)
    print("3. quatro números")
    time.sleep(0.5)